---
- name: Create Wordpress directory
  tags: 'wordpress'
  become: yes
  file:
    path: "{{ wp_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'wordpress'
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ wp_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'wordpress'
  become: yes
  docker_compose:
    project_src: "{{ wp_dir }}"
    pull: yes
    state: present
    recreate: always

    remove_orphans: yes
