---
# tasks file for show-images
# Show all available Openstack images
- name: Retrieve all available Openstack images
  os_image_info:
  register: image_result

- name: Get image names and Ids
  set_fact:
    image_facts: "{{ image_facts|default([]) + [ {'name': item.name, 'id': item.id} ] }}"
  loop: '{{ image_result.openstack_image }}'
  when: item.name is defined

- name: Show images
  debug:
    msg: "Image name: {{ item.name }}; Image id: {{ item.id }}"
  loop: '{{ image_facts }}'
